#!/usr/bin/env node
/**
 * Build script: serialize `dialogistStyles` to a plain CSS file at `dist/dialogist.css`.
 *
 * The exported `dialogistStyles` is a JSS-like static object (no theme references). This
 * script imports it from the *source* (TypeScript) using `tsx`-style on-the-fly transpile
 * via `swc-node` — but to avoid an extra runtime dependency we instead duplicate the
 * static `dialogistClasses` map and `dialogistStyles` here as a plain JS module.
 *
 * The source of truth lives in `src/theme/dialogTheme.ts` and `src/classes.ts`. This
 * script re-exports the same shape via dynamic import of the *built* artifact in `dist/`,
 * so it must run AFTER the rollup build that produces `dist/theme/dialogTheme.js`.
 *
 * Order in `package.json#scripts.build`:
 *   1. clean
 *   2. rollup -c                     (emits dist/theme/dialogTheme.js + dist/utils/cssSerialize.js)
 *   3. tsc --project tsconfig.declarations.json
 *   4. node scripts/build-styles.mjs (writes dist/dialogist.css using dist/* artifacts)
 */

import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve as resolvePath } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const repoRoot = resolvePath(__dirname, "..");
const distRoot = resolvePath(repoRoot, "dist");

const themeUrl = pathToFileURL(resolvePath(distRoot, "src", "theme", "dialogTheme.js")).href;
const serializerUrl = pathToFileURL(resolvePath(distRoot, "src", "utils", "cssSerialize.js")).href;

const { dialogistStyles } = await import(themeUrl);
const { serializeStylesToCss } = await import(serializerUrl);

const css = serializeStylesToCss(dialogistStyles);
const banner = `/* dialogist global styles - generated by scripts/build-styles.mjs */\n`;
const outPath = resolvePath(distRoot, "dialogist.css");

await mkdir(dirname(outPath), { recursive: true });
await writeFile(outPath, banner + css + "\n", "utf8");

console.log(`[dialogist] Wrote ${outPath} (${css.length} bytes)`);
